language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
addons:
  chrome: stable

before_install:
  # ../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  # Create the dummy setting file for test.
  - cp ./server/config/googleClientSecret.json.sample ./server/config/googleClientSecret.json
  - cp ./server/config/braviaSecret.json.sample ./server/config/braviaSecret.json
  - cp ./server/config/serviceAccountKey.json.sample ./server/config/serviceAccountKey.json

script:
  - npm run lint
  - npm test
  - npm run e2e

after_success:
  - rm ./server/config/googleClientSecret.json
  - rm ./server/config/braviaSecret.json
  - rm ./server/config/serviceAccountKey.json
  - npm run coveralls
  - if [ "$TRAVIS_BRANCH" == "master" -a $TRAVIS_PULL_REQUEST == false ]; then npm run build; fi

deploy:
  provider: releases
  api_key:
    secure: 5qrS1sM36Qo04DpHuW+VF5ZuglGTZIepiCe7wuzeaWLCMzaqWXvjsi/HN0tGYPVT4z3Ri0r6FmnFI+lukR9u3HrfRDPW7RIdXqH6zZ1X5ImktFmoo921dD9sV2WaBlHtulu5aBWckIVzyU1TNjOejtMvRAnHEuZ+IyhbDlDYGL3RRQaMDU+PBmZAoaa1qX/tmNIZWj65Bna7Qx2f67xK49jzhS0amNx4RJPM3RFjmbWGzDzn14eRunzwdo5nBl+hKE4KJxHMuDrbfp/GP+jEkdnzw3QyHiSx3c1mTDVG3wBELQ6Eu5x8xum9FeNGywiJBKKgEMeGKm4VpwfG/jBOKfkncPhu9r86NIGKvbbs6WZhXYIPnyI8nwclVT7/E2oMPsrn713P9uJ2Iesype0YA3XX5IlxB2UTOZwFXsxmR+nttE0OiInMVvR7D190esJiWi0h51CRhkia0vo6twmmXRhUQuoSEbistDA90jsagTjJ4GCUF3HDbzpdue6tanB9IqBzLrApzVdanWw4m3C47YP870ZIhPjWcErR0I79UH3mRB+NZKe5E9swArtRF5yeJZA931GS/KEehMzh6PnAxFB2J45bOioeyyx5z0NqDizwD020KtmkknTmEUcZYNgqZeii70LuInDca7PKWZNCszBl9uYvqt2SSEdkUi/8Vz4=
  file: dist/build.tar.gz
  skip_cleanup: true
  on:
    repo: mid0111/google-assistant-hook
