language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

addons:
  chrome: stable

before_install:
  # ../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
  - sudo apt-get install -y libavahi-compat-libdnssd-dev

scripts:
  - npm test
  - npm run e2e

after_success:
  - npm run coveralls