language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
addons:
  chrome: stable

before_install:
  # ../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  # Create the dummy setting file for test.
  - cp ./server/config/googleClientSecret.json.sample ./server/config/googleClientSecret.json
  - cp ./server/config/braviaSecret.json.sample ./server/config/braviaSecret.json
  - cp ./server/config/serviceAccountKey.json.sample ./server/config/serviceAccountKey.json

script:
  - npm run lint
  - npm test
  - npm run e2e

after_success:
  - rm ./server/config/googleClientSecret.json
  - rm ./server/config/braviaSecret.json
  - rm ./server/config/serviceAccountKey.json
  - npm run coveralls
  - if [ "$TRAVIS_BRANCH" == "master" -a $TRAVIS_PULL_REQUEST == false ]; then npm run build; fi

before_deploy:
  - git config --local user.name "mid0111"
  - git config --local user.email "m.tajima0111@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: jT6tPGT4lfDMZF/iIzbYvnHUWaUsmnPer1aaWbanFYeYI73mRrKT3JBJHJyJEkGUqyrGVhhCGCFu8+JYrBKMohcSm94h9E1XRGT5thFb3vl38Xx2/YaCB3Fl51LU3/egiVH8szHFwTzhiq1MzvVE5oho+s8uq3wcRSt2Hzum8nyfaCuPkuLtdk9S1NP605Xvy4lwI3jO2m0zvtFpvBoz+SS7OfHIEnHMpGkRv+fQ5phG/lFFhFSuw4SndAkxRGFuxVCl9AJDKX4gC+2DQ8ofq831G7yp2sfOUuhlwLMNFH/Ig0OTT0nrB106gBsTk3ISLQA+UWoB79TJqgIxLjPJfRh4IkXwMvHHWx0mj9eox/vYZArXA8p5oFY5cRmZXuAHP/lgUZ0ybKov8DFtJIq6JVU0YPV6Nek0ulNC9n7Ia2mpJaPXRTKqgguVI99SmuKlxie5ra2rDmqMbLwgycLCaik3f3PSQKeF6ejNRRMXY1rbgqcVi5urkzMKen78aBnS4AEBN4f4/ndQh2m4HCnvH2+cRAsglBCI94X2z3Rf/LzB3Mg59jcMEr0IPtsyTXTaSgNLXd9RPO/EdyqlN7J6OcnedOp960f8xHMr+PDr699sZseb3ToJas2eNsm1ecBmvLLCuI+qkyNrS2qQ6S2IhKUV3Vkv2INImhGcOVBthaI=
  file: dist/build.tar.gz
  skip_cleanup: true
  on:
    repo: mid0111/google-assistant-hook
    tags: true
    all_branches: true
